language: c
env:
 matrix:
  - COMPILER=gcc
  - COMPILER=clang

script:
 - cd build
 - CC=${COMPILER} cmake ..
 - make build_tests
 - make test

before_install:
 - wget http://balthasar.plejeck.com/up/libcmocka_0.4.0-1_i386.deb http://balthasar.plejeck.com/up/libcmocka-dev_0.4.0-1_i386.deb
 - sudo dpkg --install libcmocka_0.4.0-1_i386.deb libcmocka-dev_0.4.0-1_i386.deb
 - sudo apt-get install -y libssl-dev libjansson-dev

notifications:
 webhooks:
  - http://n.tkte.ch/h/2632/7KNPAoAbOk-otrQ8Et2cA4r_
