language: c
env:
 matrix:
  - COMPILER=gcc
  - COMPILER=clang

script:
 - cd build
 - CC=${COMPILER} cmake ..
 - make build_tests
 - make test

before_install:
 - wget https://open.cryptomilk.org/attachments/download/37/cmocka-0.4.0.tar.xz -O /tmp/cmocka.tar.xz
 - tar -xJvf /tmp/cmocka.tar.xz
 - mkdir cmocka/build && cd cmocka/build
 - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
 - make && make install
 - sudo apt-get install -y libssl-dev libjansson-dev

